<a href="https://colab.research.google.com/github/dmitry-petrov-dev/linear_algebra/blob/lesson5/HW_Lesson_5_%D0%A1%D0%B8%D0%BD%D0%B3%D1%83%D0%BB%D1%8F%D1%80%D0%BD%D0%BE%D0%B5_%D1%80%D0%B0%D0%B7%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.set_printoptions(precision=2, suppress=True)

__1.__ Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


In [3]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
A

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [4]:
U, s, W = np.linalg.svd(A)

In [5]:
# Траспонируем матрицу W
V = W.T
V

array([[ 0.07, -0.37, -0.93],
       [ 0.72,  0.67, -0.21],
       [ 0.69, -0.65,  0.31]])

In [6]:
# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
D

array([[8.82, 0.  , 0.  ],
       [0.  , 6.14, 0.  ],
       [0.  , 0.  , 2.53],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [7]:
# Матрица U
U

array([[ 0.17,  0.16, -0.53, -0.8 , -0.16],
       [ 0.39, -0.53,  0.61, -0.43,  0.03],
       [-0.14, -0.82, -0.52,  0.14,  0.07],
       [ 0.89,  0.06, -0.25,  0.38, -0.06],
       [ 0.08,  0.11, -0.08, -0.11,  0.98]])

In [8]:
# Убедимся, что матрицы U и V ортогональны
print(np.dot(U.T, U))
print(np.dot(V.T, V))

[[ 1.  0. -0. -0. -0.]
 [ 0.  1.  0.  0.  0.]
 [-0.  0.  1. -0. -0.]
 [-0.  0. -0.  1. -0.]
 [-0.  0. -0. -0.  1.]]
[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]


In [9]:
# Проверка:
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


__2__. Для матрицы из предыдущего задания найти:

  а) евклидову норму; 

  б) норму Фробениуса.

**а) евклидова норма:**

In [10]:
# Евклидова норма матрицы равна евклидовой норме диагональной матрицы из ее сингулярных чисел D. Максимальное значение полученного отношения будет равно максимальному сингулярному числу mu_max:
print(max(map(max, D)))

8.824868854820442


**б) норма Фробениуса:**

In [11]:
print(np.sqrt(np.sum(D**2)))

11.045361017187261
